// /Users/jdbernardo/Sites/alpha-model/tailwind.config.js
/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './src/**/*.{vue,js,ts,jsx,tsx}',
        './src/**/*.{html,js,ts,jsx,tsx}',
        './src/assets/main.css',
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Lato', 'ui-sans-serif', 'system-ui', 'sans-serif'],
                serif: ['Merriweather', 'ui-serif', 'Georgia', 'serif'],
                mono: ['Fira Code', 'ui-monospace', 'SFMono-Regular', 'monospace'],
            },
            fontSize: {
                xs: '0.75rem',
                sm: '0.875rem',
                base: '1rem',
                md: '1.125rem',
                lg: '1.25rem',
                xl: '1.5rem',
                '2xl': '1.75rem',
                '3xl': '2rem',
                '4xl': '2.25rem',
                '5xl': '2.5rem',
                '6xl': '2.75rem',
                h1: '6rem',
            },
            lineHeight: {
                none: '1',
                tight: '1.25',
                snug: '1.375',
                normal: '1.5',
                relaxed: '1.625',
                loose: '2',
            },
            fontWeight: {
                thin: '100',
                extralight: '200',
                light: '300',
                normal: '400',
                medium: '500',
                semibold: '600',
                bold: '700',
                extrabold: '800',
                black: '900',
            },
            colors: {
                transparent: 'transparent',
                current: 'currentColor',

                white: '#ffffff',
                black: '#000000',

                primary: {
                    50: '#f0f6ff',
                    100: '#d9e6ff',
                    200: '#a9d3ff',
                    300: '#78bfff',
                    400: '#3b82f6',
                    500: '#1565c0',
                    600: '#0d4b8c',
                    700: '#0a3d6f',
                    800: '#0a3142',
                    900: '#002333',
                    gold: '#E3007A',
                    orange: '#FF9100',
                    gold: '#e3c265',
                },

                gray: {
                    50: '#f9fafb',
                    100: '#f3f4f6',
                    200: '#e5e7eb',
                    300: '#d1d5db',
                    400: '#9ca3af',
                    500: '#6b7280',
                    600: '#4b5563',
                    700: '#374151',
                    800: '#1f2937',
                    900: '#111827',
                },
                red: {
                    50: '#fef2f2',
                    100: '#fee2e2',
                    200: '#fecaca',
                    300: '#fca5a5',
                    400: '#f87171',
                    500: '#ef4444',
                    600: '#dc2626',
                    700: '#b91c1c',
                    800: '#991b1b',
                    900: '#7f1d1d',
                },
                orange: {
                    50: '#fff7ed',
                    100: '#ffedd5',
                    200: '#fed7aa',
                    300: '#fdba74',
                    400: '#fb923c',
                    500: '#f97316',
                    600: '#ea580c',
                    700: '#c2410c',
                    800: '#9a3412',
                    900: '#7c2d12',
                },
            },
        },
    },
    plugins: [require('@tailwindcss/aspect-ratio'), require('@tailwindcss/forms')],
};
